### ISSUE TITLE
Mobile Safariでクラッシュする

### ISSUE THREAD

**Issue by logue** [shogo82148/igo-javascript#1]
iPhoneで本スクリプトを実行するとブラウザが強制終了してしまいます。
Mobile Chromeでも同じでした。

**Comment by shogo82148** [comment]
お返事遅くなりました。
iPhone 6s では正常動作したので、おそらくメモリ不足だと思います。
Mobile Safari固有の問題では無いので、一旦クローズします。

最近の端末でも再現する場合は、機種名と一緒に新しくissue作成をお願いします。
