### ISSUE TITLE
Release/bump a version?

### ISSUE THREAD

**Issue by kuanyui** [shogo82148/igo-javascript#2]
First, thanks for this great library.

The regulation of 3rd-party library usage for Firefox Addon [indicates that non-release versions of third-party libraries are not accepted](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Third_Party_Library_Usage), could you release a version (just via git tag)?

BTW, a similar issue occurs in [zipjs](https://github.com/shogo82148/zipjs), but that repo doesn't accept issue so I say here.

**Comment by shogo82148** [comment]
I just published igo-javascript v0.0.1 https://github.com/shogo82148/igo-javascript/releases/tag/v0.0.1
, zipjs v0.0.1 https://github.com/shogo82148/zipjs/releases/tag/v0.0.1 , and jsheap v0.0.1 https://github.com/shogo82148/jsheap/releases/tag/v0.0.1

Have fun!
